"""Increase password_hash length to 256

Revision ID: 907736fd9bbf
Revises: b10b3741a27a
Create Date: 2025-09-28 13:47:08.012173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907736fd9bbf'
down_revision = 'b10b3741a27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
