"""empty message

Revision ID: b10b3741a27a
Revises: 20e2fc6603e1
Create Date: 2025-09-28 13:25:59.085670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10b3741a27a'
down_revision = '20e2fc6603e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['trainer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('trainer_id')

    # ### end Alembic commands ###
