"""empty message

Revision ID: e9e5f8a739e7
Revises: 907736fd9bbf
Create Date: 2025-09-28 19:31:58.265333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e5f8a739e7'
down_revision = '907736fd9bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmi', sa.Float(), nullable=True))

    with op.batch_alter_table('workout_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_classes', schema=None) as batch_op:
        batch_op.drop_column('current_capacity')
        batch_op.drop_column('max_capacity')

    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.drop_column('bmi')

    # ### end Alembic commands ###
